url: zzz.io
title: Example Page
baseurl: /

# note: redcarpet is not supported on github pages
markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  input: GFM

remote_theme: just-the-docs/just-the-docs@v0.10.1

highlighter: rouge

